"""empty message

Revision ID: 954572dc104c
Revises: ef31f9237b41
Create Date: 2022-04-11 12:21:52.905833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954572dc104c'
down_revision = 'ef31f9237b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
