"""empty message

Revision ID: de60c8ad8db1
Revises: 954572dc104c
Create Date: 2022-04-12 12:10:41.239688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de60c8ad8db1'
down_revision = '954572dc104c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Job', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Job', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Job', type_='foreignkey')
    op.drop_column('Job', 'user_id')
    # ### end Alembic commands ###
